//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Business
    {
        [Display(Name="主键")]
        public int ID { get; set; }
        [Display(Name="业务代码")]
        public string CODE { get; set; }
         [Display(Name="业务名称")]
        public string NAME { get; set; }
        [Display(Name="业务类型")]
        public string TYPE { get; set; }

         [Display(Name="是否自动同步")]
        public Nullable<bool> ISAUTO { get; set; }

         [Display(Name="开始时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> STARTDATE { get; set; }

          [Display(Name="结束时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ENDDATE { get; set; }

        /// <summary>
        /// 值
        /// </summary>
        [Display(Name="值")]
        public Nullable<decimal> VALUE { get; set; }

        /// <summary>
        /// 时间单位
        /// </summary>
          [Display(Name="时间单位")]
        public string FREQUENCY { get; set; }
    }
}
