//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Count
    {
        public int id { get; set; }
        public int BusId { get; set; }
        public int sucsum { get; set; }
        public Nullable<int> failsum { get; set; }
        public Nullable<System.DateTime> lattime { get; set; }
        public Nullable<int> succount { get; set; }
        public Nullable<int> failcount { get; set; }
    }
}
