//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Logdetail
    {
        public int id { get; set; }
        public int busId { get; set; }
        [DisplayName("相关编码")]
        public string code { get; set; }

        [DisplayName("记录时间")]
        public string date { get; set; }

        [DisplayName("调用地址")]
        public string url { get; set; }

        [DisplayName("调用参数")]
        public string postData { get; set; }


        [DisplayName("调用方式")]
        public string postType { get; set; }


        [DisplayName("返回数据")]
        public string returnData { get; set; }


        [DisplayName("调用结果")]
        public string result { get; set; }


        [DisplayName("相关描述")]
        public string description { get; set; }


        [DisplayName("备注信息")]
        public string mark { get; set; }
    }
}
